// frontend/src/stories/button/button.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'storybook-button',
  standalone: true,
  imports: [CommonModule],
  template: ` <button
  type="button"
  (click)="onClick.emit($event)"
  [ngClass]="classes"
  [ngStyle]="{ 'background-color': backgroundColor }"
>
  {{ label }}
</button>`,
  styleUrls: ['./button.css'],
})
export class ButtonComponent {
  @Input()
  primary = false;

  @Input()
  backgroundColor?: string;

  @Input()
  size: 'small' | 'medium' | 'large' = 'medium';

  /**
   * Button contents
   *
   * @required
   */
  @Input()
  label = 'Button';

  /** Optional click handler */
  @Output()
  onClick = new EventEmitter<Event>();

  public get classes(): string[] {
    const mode = this.primary ? 'storybook-button--primary' : 'storybook-button--secondary';

    return ['storybook-button', `storybook-button--${this.size}`, mode];
  }
}

// src/stories/Button.svelte
<script>
import "./button.css";

/**
 * @typedef {Object} Props
 * @property {boolean} [primary] Is this the principal call to action on the page?
 * @property {string} [backgroundColor] What background color to use
 * @property {'small' | 'medium' | 'large'} [size] How large should the button be?
 * @property {string} label Button contents
 * @property {() => void} [onClick] The onclick event handler
 */

/** @type {Props} */
const {
	primary = false,
	backgroundColor,
	size = "medium",
	label,
	onClick,
} = $props();
</script>

<button
	type="button"
	class={['storybook-button', `storybook-button--${size}`].join(' ')}
	class:storybook-button--primary={primary}
	class:storybook-button--secondary={!primary}
	style:background-color={backgroundColor}
	onclick={onClick}
>
	{label}
</button>
