// src/lib/components/shared/Footer.svelte
<footer class="fade-in relative mt-4 dark:bg-background">
	<div class="container mx-auto px-4">
		<div class="flex flex-wrap items-center justify-center md:justify-between">
			<div class="mx-auto w-full px-4 text-center md:w-6/12">
				<div class="py-1 text-sm font-semibold">
					<a href="https://www.spsbj.sk/" class="text-2xl">
						<span class="hover-scale inline-block"> &copy; SPŠT Knižnica 2025 </span>
					</a>
				</div>
			</div>
		</div>
	</div>
</footer>

// frontend/src/app/components/footer/footer.component.ts
import { Component } from "@angular/core";

@Component({
	selector: "app-footer",
	imports: [],
	templateUrl: "./footer.component.html",
})
export class FooterComponent {}

<footer class="relative mt-4">
  <div class="container mx-auto px-4">
    <div class="flex flex-wrap items-center justify-center md:justify-between">
      <div class="mx-auto w-full px-4 text-center md:w-6/12">
        <div class="py-1 text-sm font-semibold">
          <a href="https://www.spsbj.sk/" class="text-2xl dark:text-white">
            <span class="inline-block"> &copy; SPŠT Knižnica 2025 </span>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>
